export const
  SHOW_ALERT = 'SHOW_ALERT',
  HIDE_ALERT = 'HIDE_ALERT'

export const
  SET_LOADING = 'SET_LOADING',
  NOT_FOUND = 'NOT_FOUND',
  GET_ERROR = 'GET_ERROR',
  CLEAR_RECIPES = 'CLEAR_RECIPES',
  GET_LINKS = 'GET_LINKS',
  GET_RECIPES = 'GET_RECIPES',
  GET_RECIPES_MORE = 'GET_RECIPES_MORE'

export const
  OPEN_HOME = 'OPEN_HOME',
  OPEN_ABOUT = 'OPEN_ABOUT',
  OPEN_SEARCH = 'OPEN_SEARCH',
  OPEN_MY_RECIPES = 'OPEN_MY_RECIPES',
  OPEN_AUTH = 'OPEN_AUTH',
  OPEN_RECIPE = 'OPEN_RECIPE'

export const
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  SAVE_USER_ID = 'SAVE_USER_ID'

export const
  ADD_FAVORITE_RECIPE = 'ADD_FAVORITE_RECIPE',
  DELETE_FAVORITE_RECIPE = 'DELETE_FAVORITE_RECIPE'